services:
  - type: web
    name: calltech-admin
    runtime: static
    rootDir: Admin
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://calltrack-e62l.onrender.com
